// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiAppdemo.DBContexts;

#nullable disable

namespace WebApiAppdemo.Migrations
{
    [DbContext(typeof(DinosaurDetailContext))]
    [Migration("20230718082016_FirstDataFeed")]
    partial class FirstDataFeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiAppdemo.Entities.Ages", b =>
                {
                    b.Property<int>("AgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgeId"));

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DinosaurId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AgeId");

                    b.HasIndex("DinosaurId");

                    b.ToTable("Age");

                    b.HasData(
                        new
                        {
                            AgeId = 1011,
                            Age = "Late Jurassic to late creatceous epochs",
                            Name = ""
                        },
                        new
                        {
                            AgeId = 1021,
                            Age = "Late Jurassic to late creatceous epochs",
                            Name = ""
                        },
                        new
                        {
                            AgeId = 1031,
                            Age = "Late Jurassic to late creatceous epochs",
                            Name = ""
                        },
                        new
                        {
                            AgeId = 1041,
                            Age = "Late Jurassic to late creatceous epochs",
                            Name = ""
                        },
                        new
                        {
                            AgeId = 1051,
                            Age = "Late Jurassic to late creatceous epochs",
                            Name = ""
                        });
                });

            modelBuilder.Entity("WebApiAppdemo.Entities.Dinosaur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dinosaurs");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Description = "",
                            Name = "Pterodactyl"
                        },
                        new
                        {
                            Id = 102,
                            Description = "",
                            Name = "Stegosaurus"
                        },
                        new
                        {
                            Id = 103,
                            Description = "",
                            Name = "Ankylosaurus"
                        },
                        new
                        {
                            Id = 104,
                            Description = "",
                            Name = "T-Rex"
                        },
                        new
                        {
                            Id = 105,
                            Description = "",
                            Name = "Megalosaurus"
                        });
                });

            modelBuilder.Entity("WebApiAppdemo.Models.AgeDto", b =>
                {
                    b.Property<int>("AgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgeId"));

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DinosaurId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AgeId");

                    b.HasIndex("DinosaurId");

                    b.ToTable("AgeDto");
                });

            modelBuilder.Entity("WebApiAppdemo.Entities.Ages", b =>
                {
                    b.HasOne("WebApiAppdemo.Entities.Dinosaur", "Dinosaur")
                        .WithMany()
                        .HasForeignKey("DinosaurId");

                    b.Navigation("Dinosaur");
                });

            modelBuilder.Entity("WebApiAppdemo.Models.AgeDto", b =>
                {
                    b.HasOne("WebApiAppdemo.Entities.Dinosaur", null)
                        .WithMany("Age")
                        .HasForeignKey("DinosaurId");
                });

            modelBuilder.Entity("WebApiAppdemo.Entities.Dinosaur", b =>
                {
                    b.Navigation("Age");
                });
#pragma warning restore 612, 618
        }
    }
}
