// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiAppdemo.DBContexts;

#nullable disable

namespace WebApiAppdemo.Migrations
{
    [DbContext(typeof(DinosaurDetailContext))]
    [Migration("20230717130104_DinosaurDBInitialMigration")]
    partial class DinosaurDBInitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiAppdemo.Entities.Ages", b =>
                {
                    b.Property<int>("AgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgeId"));

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DinosaurId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AgeId");

                    b.HasIndex("DinosaurId");

                    b.ToTable("Age");
                });

            modelBuilder.Entity("WebApiAppdemo.Entities.Dinosaur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dinosaurs");
                });

            modelBuilder.Entity("WebApiAppdemo.Models.AgeDto", b =>
                {
                    b.Property<int>("AgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgeId"));

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DinosaurId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AgeId");

                    b.HasIndex("DinosaurId");

                    b.ToTable("AgeDto");
                });

            modelBuilder.Entity("WebApiAppdemo.Entities.Ages", b =>
                {
                    b.HasOne("WebApiAppdemo.Entities.Dinosaur", "Dinosaur")
                        .WithMany()
                        .HasForeignKey("DinosaurId");

                    b.Navigation("Dinosaur");
                });

            modelBuilder.Entity("WebApiAppdemo.Models.AgeDto", b =>
                {
                    b.HasOne("WebApiAppdemo.Entities.Dinosaur", null)
                        .WithMany("Age")
                        .HasForeignKey("DinosaurId");
                });

            modelBuilder.Entity("WebApiAppdemo.Entities.Dinosaur", b =>
                {
                    b.Navigation("Age");
                });
#pragma warning restore 612, 618
        }
    }
}
